mysite/doixuan79/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path

app_name = "doixuan79"

urlpatterns = [
    

    path("", views.index, name="index"),
    path("gioithieu/",views.gioithieu, name="about"),
    path("sukien/",views.sukien, name="sukien"),
    path("booking/",views.booking, name="booking"),
    path("blog/",views.blog, name="blog"),
    path("lienhe/",views.lienhe, name="lienhe"),
    
    # load các trang dịch vụ
    path("buffet-lau-nuong/",views.lauNuong, name="launuong"),
    path("cafe/",views.cafe, name="cafe"),
    path("cheo-thuyen-Kayak/",views.cheothuyen, name="cheothuyen"),
    path("camping/",views.camping, name="camping"),
    path("khu-vui-choi-tre-em/",views.vuichoi, name="vuichoi"),
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include("doixuan79.urls")),
    path('admin/', admin.site.urls),
    
]

mysite/doixuan79/models.py
from django.db import models

# Create your models here.

mysite/doixuan79/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

from django.shortcuts import render

from django.http import HttpResponse
from django.core.paginator import Paginator
from django.http import JsonResponse
import json

def index(request):
    return render(request, 'pages/index.html', {})

def gioithieu(request):
    return render(request, 'pages/about.html',{})

def sukien(request):
    return render(request, 'pages/even.html',{})

def booking(request):
    return render(request, 'pages/booking.html',{})

def dichvu(request):
    return render(request, 'pages/service.html',{})

def blog(request):
    return render(request, 'pages/blog.html',{})

def lienhe(request):
    return render(request, 'pages/contact.html',{})

# View ra các trang dịch vụ
def lauNuong(request):
    return render(request, 'pages/lauNuong.html',{})
def cheothuyen(request):
    return render(request, 'pages/cheothuyen.html',{})
def cafe(request):
    return render(request, 'pages/cafe.html',{})
def camping(request):
    return render(request, 'pages/camping.html',{})
def vuichoi(request):
    return render(request, 'pages/khuvuichoi.html',{})

mysite/doixuan79/templates/elements/footer.html
<!-- Footer Start -->
<div class="container-fluid footer bg-dark text-light footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Thông Tin Liên Hệ</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Đồi Xuân, Mê Linh, Hà Nội</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>0982548792  </p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>doixuan79@gmail.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Chi Tiết</h5>
                <a class="btn btn-link" href="">Giới Thiệu</a>
                <a class="btn btn-link" href="">Liên Hệ</a>
                <a class="btn btn-link" href="">Dịch Vụ</a>
                <a class="btn btn-link" href="">Điều Khoản & Quy Định</a>
                <a class="btn btn-link" href="">Hỗ Trợ</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Chia Sẻ</h5>
                <a class="btn btn-link" href="">Giới Thiệu Lịch Sử</a>
                <a class="btn btn-link" href="">Tham Khảo </a>
                <a class="btn btn-link" href="">Đặt Chỗ</a>
                {% comment %} <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">Support</a> {% endcomment %}
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Đồi Xuân 79</h5>
                <p>Đồi Xuân 79 là chốn bình yên hoàn hảo, nơi thiên nhiên xanh mát hòa quyện với không gian thư giãn, tạo nên trải nghiệm khó quên.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

mysite/doixuan79/templates/elements/head.html
{% load static %}
<meta charset="utf-8">
<title>Du lịch | Đồi Xuân 79</title>
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="" name="keywords">
<meta content="" name="description">

<!-- Favicon -->
<link href="{% static 'doixuan/assets/img/logo.jpg' %}" rel="icon">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Quicksand:wght@600;700&display=swap" rel="stylesheet"> 

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'doixuan/assets/lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'doixuan/assets/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
<link href="{% static 'doixuan/assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'doixuan/assets/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Template Stylesheet -->
<link href="{% static 'doixuan/assets/css/style.css' %}" rel="stylesheet">

mysite/doixuan79/templates/elements/header.html
{% load static %}
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Topbar Start -->
<div class="container-fluid bg-light p-0 wow fadeIn" data-wow-delay="0.1s">
    <div class="row gx-0 d-none d-lg-flex">
        <div class="col-lg-7 px-5 text-start">
            <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                <small class="fa fa-map-marker-alt text-primary me-2"></small>
                <small>Đồi Xuân, Mê Linh, Hà Nội</small>
            </div>
            <div class="h-100 d-inline-flex align-items-center py-3">
                <small class="far fa-clock text-primary me-2"></small>
                <small>Mon - Fri : 9.00 AM - 6.00 PM</small>
            </div>
        </div>
        <div class="col-lg-5 px-5 text-end">
            <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                <small class="fa fa-phone-alt text-primary me-2"></small>
                <small>0982548792</small>
            </div>
            <div class="h-100 d-inline-flex align-items-center">
                <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-twitter"></i></a>
                <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-sm-square bg-white text-primary me-0" href=""><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top py-lg-0 px-4 px-lg-5 wow fadeIn" data-wow-delay="0.1s">
    <a href="{% url 'doixuan79:index' %}" class="navbar-brand p-0">
        <img class="img-fluid me-3" src="{% static 'doixuan/assets/img/logo.jpg' %}" alt="Icon">
        <h1 class="m-0 text-primary"></h1>
    </a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse py-4 py-lg-0" id="navbarCollapse">
        <div class="navbar-nav ms-auto">
            <a href="{% url 'doixuan79:index' %}" class="nav-item nav-link active">Trang chủ</a>
            <a href="{% url 'doixuan79:about' %}" class="nav-item nav-link">Giới thiệu</a>
            <a href="{% url 'doixuan79:sukien' %}" class="nav-item nav-link">Sự kiện và Trải nghiệm</a>
            <a href="{% url 'doixuan79:booking' %}" class="nav-item nav-link">Đặt chỗ/Booking</a>
            <div class="nav-item dropdown">
                <a href="" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Dịch vụ</a>
                <div class="dropdown-menu rounded-0 rounded-bottom m-0">
                    <a href="{% url 'doixuan79:launuong' %}" class="dropdown-item">Buffet Lẩu Nướng</a>
                    <a href="{% url 'doixuan79:cafe' %}" class="dropdown-item">Quán Cafe</a>
                    <a href="{% url 'doixuan79:cheothuyen' %}" class="dropdown-item">Chèo thuyền Kayak</a>
                    <a href="{% url 'doixuan79:camping' %}" class="dropdown-item">Camping</a>
                    <a href="{% url 'doixuan79:vuichoi' %}" class="dropdown-item">Giải trí khác</a>
                </div>
            </div>
            <a href="{% url 'doixuan79:blog' %}" class="nav-item nav-link">Blog</a>
            <a href="{% url 'doixuan79:lienhe' %}" class="nav-item nav-link">Liên hệ</a>
        </div>
    </div>
</nav>
<!-- Navbar End -->

mysite/doixuan79/templates/elements/script.html
{% load static %}

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'doixuan/assets/lib/wow/wow.min.js' %}"></script>
<script src="{% static 'doixuan/assets/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'doixuan/assets/lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'doixuan/assets/lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'doixuan/assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'doixuan/assets/lib/lightbox/js/lightbox.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'doixuan/assets/js/main.js' %}"></script>

mysite/doixuan79/templates/layout-main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        {% include "elements/head.html" %}
    </head>

    <body>

        
            {% include "elements/header.html" %}  
        


        <main>
            {% block content %}
            {% endblock  %}
        </main>

        <footer>
            {% include "elements/footer.html" %}  
        </footer>
        
        {% include "elements/script.html" %}
    </body>

</html>

mysite/doixuan79/templates/pages/about.html
{% extends "layout-main.html" %}
{% load static %}
{% block content %}


    <!-- Page Header Start -->
    <div class="container-fluid header-bg py-5 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <h1 class="display-4 text-white mb-3 animated slideInDown">About Us</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a class="text-white" href="{% url 'doixuan79:index' %}">Trang chủ</a></li>
                    <li class="breadcrumb-item text-primary active" aria-current="page">Giới thiệu</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
    <!-- menu -->

    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
                    <p><span class="text-primary me-2">#</span>Chào Mừng Đến Với</p>
                    <h1 class="display-5 mb-4">Khu Du Lịch <span class="text-primary">Đồi Xuân 79</span><nav></nav></h1>
                    <p class="mb-4">Điểm đến lý 
                        tưởng cho những ai muốn thư giãn và tái 
                        tạo năng lượng, mà còn là nơi giao thoa văn 
                        hóa và không gian để tìm về sự an yên và 
                        sâu lắng trong cuộc sống.</p>
                    <h5 class="mb-3"><i class="far fa-check-circle text-primary me-3"></i>Ẩm Thực Đặc Sắc</h5>
                    <h5 class="mb-3"><i class="far fa-check-circle text-primary me-3"></i>Tổ Chức Sự Kiện</h5>
                    <h5 class="mb-3"><i class="far fa-check-circle text-primary me-3"></i>Vui Chơi Giải Trí</h5>
                    <h5 class="mb-3"><i class="far fa-check-circle text-primary me-3"></i>Hoạt Động Văn Hóa</h5>
                    <a class="btn btn-primary py-3 px-5 mt-3" href="">Read More</a>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="img-border">
                        <img class="img-fluid" src="img/about/about.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

    <!-- ý nghĩa của logo -->
    <div class="container-xxl py-5">
        <div class="container">
            <h1 class="text-center fw-bold mb-4 wow fadeInUp" data-wow-delay="0.1s">
                Ý Nghĩa của Logo <span class="text-primary">Đồi Xuân 79</span>
            </h1>
            <div class="row text-center">
                <!-- Cột giữa (Center Column) -->
                <div class="col-lg-4 col-md-6 col-12 mb-4 d-flex flex-column align-items-center order-1 order-lg-2 wow fadeInUp" data-wow-delay="0.1s">
                    <img src="/img/about/logo-about.png" alt="UI/UX Illustration" class="img-fluid rounded mb-3">
                    <p class="text-muted">
                        Kế thừa giá trị từ thương hiệu Sen 79 Mê Linh, thương hiệu mới phát huy sáng tạo, đổi mới phù hợp thời cuộc, hướng đến bước phát triển vượt bậc trong tương lai.
                    </p>
                </div>
                <!-- Cột trái (Left Column) -->
                <div class="col-lg-4 col-md-6 col-12 mb-4 order-2 order-lg-1 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="bg-white border rounded shadow-sm py-3 px-4 rounded-pill">
                        <h4 class="text-primary fw-bold">Thanh tịnh và an yên.</h4>
                    </div>
                    <div class="bg-white border rounded shadow-sm py-3 px-4 mt-3 rounded-pill">
                        <h4 class="text-primary fw-bold">Ẩm thực phong phú và đặc sắc.</h4>
                    </div>
                    <div class="bg-white border rounded shadow-sm py-3 px-4 mt-3 rounded-pill">
                        <h4 class="text-primary fw-bold">Phát triển ý thức bảo vệ môi trường.</h4>
                    </div>
                    <div class="bg-white border rounded shadow-sm py-3 px-4 mt-3 rounded-pill">
                        <h4 class="text-primary fw-bold">Tổ chức các sự kiện cộng đồng và lễ hội văn hoá.</h4>
                    </div>
                </div>
                <!-- Cột phải (Right Column) -->
                <div class="col-lg-4 col-md-6 col-12 mb-4 order-3 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="bg-white border rounded shadow-sm py-3 px-4 rounded-pill">
                        <h4 class="text-primary fw-bold">Kết nối văn hoá và tâm linh.</h4>
                    </div>
                    <div class="bg-white border rounded shadow-sm py-3 px-4 mt-3 rounded-pill">
                        <h4 class="text-primary fw-bold">Sum vầy và kết nối gia đình, hội nhóm.</h4>
                    </div>
                    <div class="bg-white border rounded shadow-sm py-3 px-4 mt-3 rounded-pill">
                        <h4 class="text-primary fw-bold">Tăng cường sức khoẻ thể chất và tinh thần.</h4>
                    </div>
                    <div class="bg-white border rounded shadow-sm py-3 px-4 mt-3 rounded-pill">
                        <h4 class="text-primary fw-bold">Không gian nghỉ ngơi, vui chơi hoà mình với thiên nhiên.</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <!-- Facts Start -->
    <div class="container-xxl bg-primary facts my-5 py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-4 justify-content-center">
                <div class="col-md-4 col-lg-2 text-center wow fadeIn" data-wow-delay="0.1s">
                    <i class="fa fa-paw fa-3x text-primary mb-4"></i>
                    <h1 class="text-white mb-2" data-toggle="counter-up">12345</h1>
                    <p class="text-white mb-0">Sự Gắn Kết Với Thiên Nhiên</p>
                </div>
                <div class="col-md-4 col-lg-2 text-center wow fadeIn" data-wow-delay="0.3s">
                    <i class="fa fa-users fa-3x text-primary mb-4"></i>
                    <h1 class="text-white mb-2" data-toggle="counter-up">12345</h1>
                    <p class="text-white mb-0">Không Gian Thư Giãn và Nghỉ Ngơi</p>
                </div>
                <div class="col-md-4 col-lg-2 text-center wow fadeIn" data-wow-delay="0.5s">
                    <i class="fa fa-certificate fa-3x text-primary mb-4"></i>
                    <h1 class="text-white mb-2" data-toggle="counter-up">12345</h1>
                    <p class="text-white mb-0">Sự Khám Phá và Phiêu Lưu</p>
                </div>
                <div class="col-md-4 col-lg-2 text-center wow fadeIn" data-wow-delay="0.7s">
                    <i class="fa fa-shield-alt fa-3x text-primary mb-4"></i>
                    <h1 class="text-white mb-2" data-toggle="counter-up">12345</h1>
                    <p class="text-white mb-0">Ngọn Lửa của Kết Nối và Ấm Áp</p>
                </div>
                <div class="col-md-4 col-lg-2 text-center wow fadeIn" data-wow-delay="0.9s">
                    <i class="fa fa-heart fa-3x text-primary mb-4"></i>
                    <h1 class="text-white mb-2" data-toggle="counter-up">12345</h1>
                    <p class="text-white mb-0">Biểu Tưởng của Mơ Mộng và Hy Vọng</p>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Facts End -->


    <!-- Testimonial Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <h1 class="display-5 text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Tổ Hợp Dịch Vụ tại <span class="text-primary">Đồi Xuân 79</span><nav></nav></h1>
            <!-- <h1 class="display-5 text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Tổ Hợp Dịch Vụ tại 79 Đồi Xuân!</h1> -->
            <div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
                <div class="testimonial-item text-center">
                    <img class="img-fluid rounded-circle border border-2 p-2 mx-auto mb-4" src="img/about/logo-eden.png" style="width: 150px; height: 150px;">
                    <div class="testimonial-text rounded text-center p-4">
                        <h5 class="mb-1">Eden Coffee - Vườn địa đàng</h5>
                        <p>79 Eden Coffee không chỉ là quán cafe mà còn là bức tranh thiên nhiên sống động, nơi con người tìm về sự mộc mạc và tinh khiết. Với kiến trúc hài hòa, cảnh sắc trữ tình, và không gian xanh ngát, đây là điểm đến lý tưởng để hòa mình vào thiên nhiên và văn hóa.</p>
                        <span class="fst-italic">Profession</span>
                    </div>
                </div>
                <div class="testimonial-item text-center">
                    <img class="img-fluid rounded-circle border border-2 p-2 mx-auto mb-4" src="img/about/logo-buffet.png" style="width: 150px; height: 150px;">
                    <div class="testimonial-text rounded text-center p-4">
                        <h5 class="mb-1">79 Buffet Hàn Quốc</h5>
                        <p>79 Buffet Hàn Quốc mang đến không gian ẩm thực đậm chất xứ sở Kim Chi với mô hình lẩu buffet topokki hấp dẫn, là điểm đến không thể bỏ lỡ cho các bạn trẻ. Thực khách tự do lựa chọn sốt lẩu, topping hoặc tùy chỉnh hương vị theo sở thích, tạo nên trải nghiệm ẩm thực phong phú và đa dạng.</p>
                        <span class="fst-italic">Profession</span>
                    </div>
                </div>
                <div class="testimonial-item text-center">
                    <img class="img-fluid rounded-circle border border-2 p-2 mx-auto mb-4" src="img/about/logo-lau.png" style="width: 150px; height: 150px;">
                    <div class="testimonial-text rounded text-center p-4">
                        <h5 class="mb-1">79 Lẩu hơi Hồng Kông</h5>
                        <p>79 Lẩu hơi Hồng Kông mang đến trải nghiệm ẩm thực lành mạnh với các nguyên liệu organic được nuôi trồng ngay tại Đồi Xuân 79. Phong cách lẩu hơi độc đáo kết hợp cùng nguồn nguyên liệu tươi sạch giữ trọn hương vị tự nhiên, đảm bảo sức khỏe, mang lại trải nghiệm ẩm thực xanh, bền vững và tinh tế.</p>
                        <span class="fst-italic">Profession</span>
                    </div>
                </div>
                <div class="testimonial-item text-center">
                    <img class="img-fluid rounded-circle border border-2 p-2 mx-auto mb-4" src="img/about/logo-the-hill.png" style="width: 150px; height: 150px;">
                    <div class="testimonial-text rounded text-center p-4">
                        <h5 class="mb-1">79 The Hill Event Garden</h5>
                        <p>79 The Hill Event Garden là quần thể giải trí kết hợp các dịch vụ FnB tại Đồi Xuân 79, nơi tổ chức liên tục các sự kiện như trò chơi, thể thao, teambuilding, cắm trại, lễ hội, tiệc cưới ngoài trời, và các sự kiện văn hóa theo lịch trình hoặc yêu cầu đối tác.</p>
                        <span class="fst-italic">Profession</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Testimonial End -->
        



{% endblock %}